# Generated by Django 3.1.5 on 2021-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('publisher', models.CharField(max_length=60)),
            ],
        ),
    ]
